In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv('tech_job_market_2019_2026.csv')
df.head(10)

,job_id,company_name,company_type,sector,company_size_employees,hq_country,job_role,seniority_level,years_experience_min,years_experience_max,...,application_deadline,date_position_filled,position_status,number_of_applicants,number_of_interview_rounds,offers_extended,offers_accepted,salary_min_usd,salary_max_usd,layoff_within_12_months_flag
0,JOB041385,CobaltWealth,MNC,HealthTech,146085,Germany,SOC Analyst,Mid,3,5,...,2023-11-12 00:00:00,2023-11-20,Filled,98.0,4.0,5.0,5.0,-1,-1,N
1,JOB018462,DriftLearn,Mid-size,Cloud/Infra,5882,USA,Mobile Engineer (iOS),Mid,1,4,...,2025-06-29 00:00:00,NaN,Open,134.0,2.0,1.0,0.0,NaN,NaN,No
2,JOB110011,AnchorBuzz Labs,MNC,HealthTech,186507,USA,QA Engineer,Lead,7,15,...,2026-01-24 00:00:00,2026-02-08,Filled,36.0,4.0,1.0,1.0,238800.0,274700.0,0
3,JOB073462,KiteSphere,Unicorn,HealthTech,10930,Brazil,Research Scientist,Entry,1,4,...,2020-12-09 00:00:00,2020-12-21,Filled,300.0,1.0,6.0,5.0,96300.0,104000.0,Yes
4,JOB051683,AetherNode Co,MNC,Social/AdTech,42510,USA,Product Manager,Senior,6,9,...,2025-07-19 00:00:00,2025-09-15,Filled,43.0,3.0,1.0,1.0,"$186,800",245400.0,1
5,JOB099770,QuantumBuzz Technologies,MNC,SaaS,86535,UK,Data Engineer,Intern,1,1,...,2025-09-09 00:00:00,2025-09-09,Filled,58.0,2.0,1.0,1.0,33100.0,38500.0,No
6,JOB080320,SpireCloud,MNC,Fintech,369939,USA,UI Designer,Entry,0,1,...,2022-06-16 00:00:00,2022-06-09,Filled,281.0,1.0,1.0,3.0,87400.0,98100.0,False
7,JOB057551,EchoCortex Co,MNC,Cybersecurity,128882,USA,Embedded Systems Engineer,Entry,0,4,...,2024-05-25 00:00:00,2024-05-29,Filled,258.0,3.0,1.0,1.0,131100.0,103900.0,N
8,JOB019108,NimbusFlow,FAANG-tier,Crypto/Web3,53256,UK,Product Designer,Mid,1,5,...,2022-04-21 00:00:00,2022-08-17,Filled,78.0,4.0,1.0,1.0,114500.0,139700.0,0
9,JOB088302,VantageChain Systems,Startup,AI/ML,380,Brazil,Product Designer,Intern,0,0,...,2025-05-23 00:00:00,2025-05-05,Filled,349.0,3.0,1.0,1.0,42500.0,47600.0,False

In [7]:
df.shape

(115000, 28)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115000 entries, 0 to 114999
Data columns (total 28 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   job_id                        115000 non-null  object
 1   company_name                  115000 non-null  object
 2   company_type                  115000 non-null  object
 3   sector                        115000 non-null  object
 4   company_size_employees        115000 non-null  int64
 5   hq_country                    115000 non-null  object
 6   job_role                      115000 non-null  object
 7   seniority_level               115000 non-null  object
 8   years_experience_min          115000 non-null  int64
 9   years_experience_max          115000 non-null  int64
 10  required_tech_stack           115000 non-null  object
 11  primary_programming_language  92525 non-null   object
 12  work_mode                     115000 non-null  object
 13  visa_sponsorship_offered      115000 non-null  object
 14  job_location_country          115000 non-null  object
 15  job_location_city             89893 non-null   object
 16  salary_currency               115000 non-null  object
 17  posting_date                  115000 non-null  object
 18  application_deadline          109243 non-null  object
 19  date_position_filled          89219 non-null   object
 20  position_status               115000 non-null  object
 21  number_of_applicants          113890 non-null  float64
 22  number_of_interview_rounds    114564 non-null  float64
 23  offers_extended               114670 non-null  float64
 24  offers_accepted               114670 non-null  float64
 25  salary_min_usd                111682 non-null  object
 26  salary_max_usd                111682 non-null  object
 27  layoff_within_12_months_flag  115000 non-null  object
dtypes: float64(4), int64(3), object(21)
memory usage: 24.6+ MB

## there 21 object columns, 7 int columns

In [14]:
df.isnull().sum().sum()

np.int64(87962)

In this data there are 87962 missing data

In [15]:
df.isnull().sum().sort_values(ascending=False)

date_position_filled            25781
job_location_city               25107
primary_programming_language    22475
application_deadline             5757
salary_max_usd                   3318
salary_min_usd                   3318
number_of_applicants             1110
number_of_interview_rounds        436
offers_accepted                   330
offers_extended                   330
job_id                              0
position_status                     0
posting_date                        0
salary_currency                     0
job_location_country                0
company_name                        0
visa_sponsorship_offered            0
work_mode                           0
required_tech_stack                 0
years_experience_max                0
years_experience_min                0
seniority_level                     0
job_role                            0
hq_country                          0
company_size_employees              0
sector                              0
company_type                        0
layoff_within_12_months_flag        0
dtype: int64

In [16]:
df.describe()

,company_size_employees,years_experience_min,years_experience_max,number_of_applicants,number_of_interview_rounds,offers_extended,offers_accepted
count,115000.000000,115000.000000,115000.000000,113890.000000,114564.000000,114670.000000,114670.000000
mean,105386.103122,3.004452,6.665443,181.659215,3.307653,1.349786,1.196634
std,102117.290040,3.093383,5.073654,436.344753,1.418283,1.457267,1.122837
min,10.000000,0.000000,0.000000,-5.000000,1.000000,0.000000,0.000000
25%,6038.750000,1.000000,3.000000,62.000000,2.000000,1.000000,1.000000
50%,88364.000000,2.000000,6.000000,119.000000,3.000000,1.000000,1.000000
75%,169840.250000,5.000000,9.000000,213.000000,4.000000,1.000000,1.000000
max,488674.000000,24.000000,24.000000,36816.000000,8.000000,8.000000,10.000000

1. In no of applicant min value is -5 which not possible 
2. for company_size_employees, number_of_applicants, offers_accepted, offers_extended Mean and sd is similar means it is highly spreadable

In [28]:
df[df["job_id"].duplicated()].sort_values("job_id")

,job_id,company_name,company_type,sector,company_size_employees,hq_country,job_role,seniority_level,years_experience_min,years_experience_max,...,application_deadline,date_position_filled,position_status,number_of_applicants,number_of_interview_rounds,offers_extended,offers_accepted,salary_min_usd,salary_max_usd,layoff_within_12_months_flag
97744,JOB000012,KiteCare,Startup,Crypto/Web3,270,Brazil,DevOps Engineer,Lead,7,14,...,2022-09-14 00:00:00,2022-09-18,Filled,28.0,4.0,NaN,NaN,166200.0,205100.0,Y
64353,JOB000048,MeridianShield Labs,MNC,Social/AdTech,178480,India,Full Stack Engineer,Senior,5,11,...,2026-05-29 00:00:00,2026-06-12,Filled,93.0,3.0,1.0,1.0,139500.0,186300.0,No
48411,JOB000066,PinnacleBlock Inc,MNC,Cloud/Infra,40537,UK,Mobile Engineer (Android),Senior,6,9,...,2022-11-12 00:00:00,2022-12-05,Filled,71.0,3.0,5.0,5.0,160000.0,202200.0,1
59499,JOB000091,NexusCompute,FAANG-tier,Crypto/Web3,138397,Brazil,Cloud Engineer,Intern,1,1,...,2019-02-20 00:00:00,NaN,Cancelled,221.0,4.0,0.0,0.0,48300.0,61400.0,False
103282,JOB000141,GroveCapital,Startup,E-commerce,333,India,DevOps Engineer,Entry,0,2,...,2022-02-07 00:00:00,NaN,Filled,128.0,2.0,1.0,1.0,59000.0,64900.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17090,JOB111693,DriftDesk,Startup,SaaS,443,Germany,Product Manager,Mid,1,5,...,2022-02-19 00:00:00,NaN,Open,279.0,2.0,1.0,0.0,99200.0,127700.0,N
65945,JOB111860,SpireCloud,MNC,Fintech,241384,USA,Machine Learning Engineer,Mid,3,5,...,2019-09-12 00:00:00,2019-09-21,Filled,99.0,4.0,1.0,1.0,97000.0,114200.0,0
71126,JOB111885,NexusToken Technologies,Startup,Cloud/Infra,370,Australia,Machine Learning Engineer,Entry,0,1,...,2026-09-25 00:00:00,NaN,Open,119.0,1.0,6.0,4.0,64500.0,79900.0,0
36330,JOB111985,EmberReach Technologies,FAANG-tier,HealthTech,68660,UK,Machine Learning Engineer,Mid,2,5,...,2023-06-10 00:00:00,2023-07-18,Filled,153.0,4.0,1.0,1.0,125100.0,166000.0,N
51712,JOB112036,HalcyonCampus Technologies,Mid-size,Social/AdTech,1214,Germany,Backend Engineer,Senior,4,9,...,NaN,2025-02-28,Filled,52.0,5.0,1.0,1.0,Not Disclosed,Not Disclosed,N

,job_id,company_name,company_type,sector,company_size_employees,hq_country,job_role,seniority_level,years_experience_min,years_experience_max,...,application_deadline,date_position_filled,position_status,number_of_applicants,number_of_interview_rounds,offers_extended,offers_accepted,salary_min_usd,salary_max_usd,layoff_within_12_months_flag
1584,JOB002656,DriftGame Co,MNC,EdTech,156326,USA,Data Scientist,Senior,6,8,...,2024-02-19 00:00:00,2024-02-07,Filled,99.0,5.0,1.0,1.0,153600.0,188500.0,False
2216,JOB000563,NexusCompute,FAANG-tier,Crypto/Web3,142214,Brazil,DevOps Engineer,Senior,4,10,...,2019-08-31 00:00:00,2019-09-22,Filled,90.0,4.0,1.0,1.0,185600.0,247000.0,1
2969,JOB073226,BeaconPixel,MNC,Cloud/Infra,74335,Germany,Backend Engineer,Mid,1,4,...,2022-09-14 00:00:00,NaN,Cancelled,244.0,2.0,0.0,0.0,139200.0,168900.0,No
3897,JOB022039,BeaconStack Co,MNC,AI/ML,277054,USA,Infrastructure Engineer,Entry,0,2,...,2026-01-24 00:00:00,2026-03-21,Filled,123.0,3.0,1.0,1.0,99300.0,119700.0,N
4327,JOB006733,SummitShield Co,Mid-size,E-commerce,5508,UK,Platform Engineer,Senior,5,11,...,2021-03-26 00:00:00,2021-05-07,Filled,54.0,4.0,1.0,1.0,92900.0,120300.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114639,JOB110813,BeaconStack Co,MNC,AI/ML,245179,USA,Mobile Engineer (Android),Entry,0,2,...,2019-05-09 00:00:00,NaN,Cancelled,249.0,3.0,0.0,0.0,NaN,NaN,False
114824,JOB100893,AnchorBuzz Labs,MNC,HealthTech,157695,USA,QA Engineer,Intern,0,1,...,2023-04-30 00:00:00,2023-05-11,Filled,322.0,3.0,1.0,1.0,27700.0,36300.0,False
114866,JOB110283,CobaltWealth,MNC,HealthTech,136976,Germany,Embedded Systems Engineer,Senior,5,8,...,NaN,2021-05-15,Filled,77.0,5.0,1.0,1.0,-1,-1,False
114871,JOB035395,AetherAI Co,MNC,AI/ML,208677,UK,Infrastructure Engineer,Lead,7,15,...,2020-08-06 00:00:00,2020-09-11,Filled,30.0,6.0,1.0,1.0,296800.0,363500.0,No
114982,JOB006051,LumenArcade Technologies,MNC,Logistics,139163,France,Product Manager,Mid,2,5,...,NaN,2025-12-12,Filled,60.0,4.0,1.0,1.0,97100.0,118200.0,0